-- Schema khởi tạo theo ảnh mô hình
-- Lưu ý: Điều chỉnh kích thước cột hoặc ràng buộc theo nhu cầu thực tế.

CREATE TABLE Khoa (
  KhoaId INT IDENTITY(1,1) PRIMARY KEY,
  MaKhoa NVARCHAR(50),
  TenKhoa NVARCHAR(255),
  GhiChu NVARCHAR(1000),
  CreatedAt DATETIME2 NOT NULL DEFAULT SYSDATETIME()
);

CREATE TABLE KhoaHoc (
  KhoaHocId INT IDENTITY(1,1) PRIMARY KEY,
  MaKhoaHoc NVARCHAR(50),
  NamBatDau INT NOT NULL,
  NamKetThuc INT NOT NULL,
  GhiChu NVARCHAR(1000),
  CreatedAt DATETIME2 NOT NULL DEFAULT SYSDATETIME()
);

CREATE TABLE Lop (
  LopId INT IDENTITY(1,1) PRIMARY KEY,
  MaLop NVARCHAR(50),
  TenLop NVARCHAR(255),
  KhoaId INT NOT NULL,
  KhoaHocId INT NOT NULL,
  GhiChu NVARCHAR(1000),
  CreatedAt DATETIME2 NOT NULL DEFAULT SYSDATETIME(),
  CONSTRAINT FK_Lop_Khoa FOREIGN KEY (KhoaId) REFERENCES Khoa(KhoaId),
  CONSTRAINT FK_Lop_KhoaHoc FOREIGN KEY (KhoaHocId) REFERENCES KhoaHoc(KhoaHocId)
);

CREATE TABLE SinhVien (
  SinhVienId INT IDENTITY(1,1) PRIMARY KEY,
  MaSV NVARCHAR(50),
  HoTen NVARCHAR(255),
  GioiTinh NVARCHAR(10),
  NgaySinh DATE NULL,
  Email NVARCHAR(255),
  FacebookId NVARCHAR(255),
  DienThoai NVARCHAR(30),
  KhoaId INT NULL,
  KhoaHocId INT NULL,
  LopId INT NULL,
  NgayTotNghiep DATE NULL,
  DiaChi NVARCHAR(500),
  CreatedAt DATETIME2 NOT NULL DEFAULT SYSDATETIME(),
  CONSTRAINT FK_SV_Khoa FOREIGN KEY (KhoaId) REFERENCES Khoa(KhoaId),
  CONSTRAINT FK_SV_KhoaHoc FOREIGN KEY (KhoaHocId) REFERENCES KhoaHoc(KhoaHocId),
  CONSTRAINT FK_SV_Lop FOREIGN KEY (LopId) REFERENCES Lop(LopId)
);

CREATE TABLE CoQuan (
  CoQuanId INT IDENTITY(1,1) PRIMARY KEY,
  TenCoQuan NVARCHAR(255),
  NganhNghe NVARCHAR(255),
  DiaChi NVARCHAR(500),
  Website NVARCHAR(255),
  CreatedAt DATETIME2 NOT NULL DEFAULT SYSDATETIME()
);

CREATE TABLE ViecLam (
  ViecLamId INT IDENTITY(1,1) PRIMARY KEY,
  SinhVienId INT NOT NULL,
  CoQuanId INT NULL,
  TenCoQuanTuyDo NVARCHAR(255),
  ChucDanh NVARCHAR(255),
  MoTaCongViec NVARCHAR(2000),
  NgayVaoLam DATE NULL,
  NgayKetThuc DATE NULL,
  Luong DECIMAL(18,2) NULL,
  DonViTienTe NVARCHAR(10),
  DungChuyenNganh BIT NULL,
  LoaiHinh NVARCHAR(100),
  CreatedAt DATETIME2 NOT NULL DEFAULT SYSDATETIME(),
  CONSTRAINT FK_VL_SV FOREIGN KEY (SinhVienId) REFERENCES SinhVien(SinhVienId),
  CONSTRAINT FK_VL_CQ FOREIGN KEY (CoQuanId) REFERENCES CoQuan(CoQuanId)
);

CREATE TABLE MucLuong (
  MucLuongId INT IDENTITY(1,1) PRIMARY KEY,
  Nhan NVARCHAR(100),
  MinLuong DECIMAL(18,2) NULL,
  MaxLuong DECIMAL(18,2) NULL,
  ThuTu INT NOT NULL DEFAULT 0
);

CREATE TABLE ThongBaoLich (
  ThongBaoLichId INT IDENTITY(1,1) PRIMARY KEY,
  SinhVienId INT NOT NULL,
  Kenh NVARCHAR(50),
  TanSuat NVARCHAR(50),
  Active BIT NOT NULL DEFAULT 1,
  NextRunAt DATETIME2 NULL,
  LastRunAt DATETIME2 NULL,
  GhiChu NVARCHAR(500),
  CreatedAt DATETIME2 NOT NULL DEFAULT SYSDATETIME(),
  CONSTRAINT FK_TBL_SV FOREIGN KEY (SinhVienId) REFERENCES SinhVien(SinhVienId)
);

